language: python
python:
 - "3.5"
 - "3.4"
 - "pypy"
cache: pip
services:
 - redis-server
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter
script:
 - python setup.py nosetests --with-coverage
after_success:
 - codeclimate-test-reporter
